// embed-logo.mjs — bakes the K Saloon logo into the backend as a base64 data URI.
//
// The backend ships as a single `deno compile` exe with no asset files on disk,
// so the receipt embeds the logo inline. Re-run this whenever the logo changes:
//   node scripts/embed-logo.mjs
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, "..");

const SRC = resolve(root, "K-Saloon.svg");
const BACKEND_OUT = resolve(root, "backend", "logo.ts");
const RENDERER_OUT = resolve(root, "renderer", "src", "assets", "K-Saloon.svg");

const bytes = readFileSync(SRC);
const dataUri = `data:image/svg+xml;base64,${bytes.toString("base64")}`;

writeFileSync(
  BACKEND_OUT,
  `// AUTO-GENERATED by scripts/embed-logo.mjs — do not edit by hand.\n` +
    `// Source: K-Saloon.svg (${bytes.length} bytes).\n` +
    `export const LOGO_DATA_URI =\n  ${JSON.stringify(dataUri)};\n`,
);

// Keep a copy where Vite can import it as a hashed asset for the UI.
mkdirSync(dirname(RENDERER_OUT), { recursive: true });
writeFileSync(RENDERER_OUT, bytes);

console.log(
  `embedded logo: ${bytes.length} bytes -> backend/logo.ts (${dataUri.length} chars) + renderer/src/assets/`,
);
